### ISSUE TITLE
Remix home page on CKAN

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/ckanext-snap_theme#14]
Show the Seach, a list of all tags, then below that the list of all data sets (can be in CKAN's version of "natural order," which puts the most popular ones first).

**Comment by takurkowski** [comment]
this page:
http://ckan.snap.uaf.edu/

"Search our data" as it looks now.

Below the search spanning the width of the page, a tag cloud listing all tags in natural order

Below the search, in the 1 or 2 columns, a list all data (with pages)

Delete the featured and statistics sections

**Comment by brucecrevensten** [comment]
Possibly useful for dev here are these things:

https://github.com/ckan/ckan/tree/release-v2.2.3/ckan/templates/snippets
