### ISSUE TITLE
Markdown table formatting (i.e.  --- | --- | ---), does not display as a table in CKAN.

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/ckanext-snap_theme#18]

**Comment by brucecrevensten** [comment]
[There are no tables in Markdown](http://meta.stackexchange.com/questions/73566/is-there-any-markdown-to-create-tables).

**Comment by takurkowski** [comment]
I need to edit the abstracts then.

**Comment by takurkowski** [comment]
simplified one record and the linked to github based metadata:
http://ckan.snap.uaf.edu/dataset/land-cover-v0-4
