### ISSUE TITLE
Need to confirm we have this as a license choice in the CKAN add data GUI

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/ckanext-snap_theme#23]
http://creativecommons.org/licenses/by-nc-sa/3.0/

**Comment by brucecrevensten** [comment]
All we have to do for this is to ensure, when we deploy, that `/etc/ckan/default/production.ini` has the following line present:

`licenses_group_url = file:///usr/lib/ckan/default/src/ckanext-snap_harvester/cka
next/snap_harvester/licenses.json`
