### ISSUE TITLE
provide preview of actual data on data record page (could be combined with extent preview)

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/ckanext-snap_theme#3]

**Comment by takurkowski** [comment]
this could be using the large thumbnails that are manually created and then uploaded into Geonetwork, or even better, just access a file (geotiff) within /CKAN_data and display via the extent preview map with some default colors.

**Comment by brucecrevensten** [comment]
Accessing the thumbnails/previews via GeoNetwork V2.6 is a no-go, we'd need to upgrade to V2.10 before seeing if that's possible.

However, pointing to a preview image on `demeter` would totally work and that's way, way simpler in terms of coding.  We'll already have the endpoint to our data directory inside GeoNetwork, so if we always have a file named 'preview.gtiff' or similar, we should be good.  (Note that we may need to use non-referenced JPEG and just use Leaflet's [imageOverlay](http://leafletjs.com/reference.html#imageoverlay) to do this in a very low-friction way).

Worth a try!  I'm going to give one a go today.
