### ISSUE TITLE
map preview not showing a map

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/ckanext-snap_theme#36]

**Comment by brucecrevensten** [comment]
Can you provide more detail on where you're seeing this?

**Comment by brucecrevensten** [comment]
MapQuest discontinued access to tiles.  Will switch to OpenStreetMap.

**Comment by brucecrevensten** [comment]
Switched to a basic terrain layer from Stamen.  We could modify this if required in the future, but closing for now!
